<a href="https://colab.research.google.com/github/om0401/PRACTICE_OF_DATA_SCIENCE/blob/main/EDA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data =pd.read_csv("Iris.csv")

In [3]:
data.head()

   sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [5]:
labelencoder = LabelEncoder()
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [6]:
data1

     sepal length  sepal width  petal length  petal width  iris
0             5.1          3.5           1.4          0.2     0
1             4.9          3.0           1.4          0.2     0
2             4.7          3.2           1.3          0.2     0
3             4.6          3.1           1.5          0.2     0
4             5.0          3.6           1.4          0.2     0
..            ...          ...           ...          ...   ...
145           6.7          3.0           5.2          2.3     2
146           6.3          2.5           5.0          1.9     2
147           6.5          3.0           5.2          2.0     2
148           6.2          3.4           5.4          2.3     2
149           5.9          3.0           5.1          1.8     2

[150 rows x 5 columns]

### One Hot Encoder

#### Using sklearn

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
data2=pd.read_csv("Iris.csv")

In [9]:
data2

     sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [10]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [11]:
# passing bridge-types-cat column (label encoded values of bridge_types
enc_df = pd.DataFrame(enc.fit_transform(data2[['iris']]).toarray())

In [12]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [13]:
# merge with main df 
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     sepal length  sepal width  petal length  petal width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

#### Using Pandas

In [14]:
import pandas as pd

In [15]:
data3 =pd.read_csv("Iris.csv")

In [16]:
data_encoded=pd.get_dummies(data3)

In [17]:
data_encoded

     sepal length  sepal width  ...  iris_Iris-versicolor  iris_Iris-virginica
0             5.1          3.5  ...                     0                    0
1             4.9          3.0  ...                     0                    0
2             4.7          3.2  ...                     0                    0
3             4.6          3.1  ...                     0                    0
4             5.0          3.6  ...                     0                    0
..            ...          ...  ...                   ...                  ...
145           6.7          3.0  ...                     0                    1
146           6.3          2.5  ...                     0                    1
147           6.5          3.0  ...                     0                    1
148           6.2          3.4  ...                     0                    1
149           5.9          3.0  ...                     0                    1

[150 rows x 7 columns]

#### IsolationForest

In [18]:
from sklearn.ensemble import IsolationForest

In [19]:
data =pd.read_csv("Iris.csv")
data_encoded=pd.get_dummies(data)

In [20]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

IsolationForest(contamination=0.01, random_state=10)

In [21]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [22]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [23]:
data_encoded

     sepal length  sepal width  ...  iris_Iris-versicolor  iris_Iris-virginica
0             5.1          3.5  ...                     0                    0
1             4.9          3.0  ...                     0                    0
2             4.7          3.2  ...                     0                    0
3             4.6          3.1  ...                     0                    0
4             5.0          3.6  ...                     0                    0
..            ...          ...  ...                   ...                  ...
145           6.7          3.0  ...                     0                    1
146           6.3          2.5  ...                     0                    1
147           6.5          3.0  ...                     0                    1
148           6.2          3.4  ...                     0                    1
149           5.9          3.0  ...                     0                    1

[150 rows x 7 columns]

In [24]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [25]:
data_encoded

     sepal length  sepal width  ...  iris_Iris-versicolor  iris_Iris-virginica
0             5.1          3.5  ...                     0                    0
1             4.9          3.0  ...                     0                    0
2             4.7          3.2  ...                     0                    0
3             4.6          3.1  ...                     0                    0
4             5.0          3.6  ...                     0                    0
..            ...          ...  ...                   ...                  ...
146           6.3          2.5  ...                     0                    1
147           6.5          3.0  ...                     0                    1
148           6.2          3.4  ...                     0                    1
149           5.9          3.0  ...                     0                    1
150          20.0         40.0  ...                     0                    0

[151 rows x 7 columns]

In [26]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [27]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [28]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [29]:
data_encoded

     sepal length  sepal width  ...    scores  anomaly
0             5.1          3.5  ...  0.202676        1
1             4.9          3.0  ...  0.177986        1
2             4.7          3.2  ...  0.176065        1
3             4.6          3.1  ...  0.181422        1
4             5.0          3.6  ...  0.194889        1
..            ...          ...  ...       ...      ...
146           6.3          2.5  ...  0.137119        1
147           6.5          3.0  ...  0.179265        1
148           6.2          3.4  ...  0.118457        1
149           5.9          3.0  ...  0.148669        1
150          20.0         40.0  ... -0.289272       -1

[151 rows x 9 columns]

In [30]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

     sepal length  sepal width  ...    scores  anomaly
106           4.9          2.5  ... -0.008885       -1
150          20.0         40.0  ... -0.289272       -1

[2 rows x 9 columns]

### PPS score

In [31]:
#install the package
!pip install ppscore

Requirement already satisfied: ppscore in /usr/local/lib/python3.7/dist-packages (1.2.0)
Requirement already satisfied: scikit-learn<1.0.0,>=0.20.2 in /usr/local/lib/python3.7/dist-packages (from ppscore) (0.24.2)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ppscore) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.4.1)

In [32]:
import ppscore as pps

In [34]:
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "sepal length", "petal length")

{'baseline_score': 1.488,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'model': DecisionTreeRegressor(),
 'model_score': 0.6687445810472126,
 'ppscore': 0.5505748783284862,
 'x': 'sepal length',
 'y': 'petal length'}

In [35]:
#calculate the whole PPS matrix
pps.matrix(data)

               x             y  ...  model_score                     model
0   sepal length  sepal length  ...     1.000000                      None
1   sepal length   sepal width  ...     0.362073   DecisionTreeRegressor()
2   sepal length  petal length  ...     0.668745   DecisionTreeRegressor()
3   sepal length   petal width  ...     0.367090   DecisionTreeRegressor()
4   sepal length          iris  ...     0.658333  DecisionTreeClassifier()
5    sepal width  sepal length  ...     0.683364   DecisionTreeRegressor()
6    sepal width   sepal width  ...     1.000000                      None
7    sepal width  petal length  ...     1.238354   DecisionTreeRegressor()
8    sepal width   petal width  ...     0.561646   DecisionTreeRegressor()
9    sepal width          iris  ...     0.469180  DecisionTreeClassifier()
10  petal length  sepal length  ...     0.325573   DecisionTreeRegressor()
11  petal length   sepal width  ...     0.313815   DecisionTreeRegressor()
12  petal length  petal length  ...     1.000000                      None
13  petal length   petal width  ...     0.164408   DecisionTreeRegressor()
14  petal length          iris  ...     0.925512  DecisionTreeClassifier()
15   petal width  sepal length  ...     0.421535   DecisionTreeRegressor()
16   petal width   sepal width  ...     0.242626   DecisionTreeRegressor()
17   petal width  petal length  ...     0.299131   DecisionTreeRegressor()
18   petal width   petal width  ...     1.000000                      None
19   petal width          iris  ...     0.953215  DecisionTreeClassifier()
20          iris  sepal length  ...     0.404204   DecisionTreeRegressor()
21          iris   sepal width  ...     0.267220   DecisionTreeRegressor()
22          iris  petal length  ...     0.319249   DecisionTreeRegressor()
23          iris   petal width  ...     0.157863   DecisionTreeRegressor()
24          iris          iris  ...     1.000000                      None

[25 rows x 9 columns]